ERC20：support approve operation
iotexproject/iotex-dapp-sample pull request #31
Opened 2021-12-21 11:41 UTC by Bigdragon123

show allowance and aproove button

2021-12-22 07:10 UTC, uu-z requested changes

2021-12-22 07:10 UTC, uu-z commented on public/translations/zh_CN.json
> +  "approve": "认证",
认证 -> 授权

2021-12-22 07:10 UTC, uu-z commented on src/pages/erc20.tsx
> +      return store.curToken?.transfer.loading || store.curToken?.approve.loading;
we could remove loading and just use `transfer.loading` or `approve.loading` for each button

2021-12-24 11:13 UTC, Bigdragon123 commented on src/pages/erc20.tsx
> +      return store.curToken?.transfer.loading || store.curToken?.approve.loading;
already edited

2021-12-25 05:39 UTC, uu-z commented
![image](https://user-images.githubusercontent.com/12439992/147378249-81a4e59e-8587-49bd-b28c-d99a2cc4d031.png)
approve button shoud start loading when sending tx

2021-12-25 05:40 UTC, uu-z commented
![image](https://user-images.githubusercontent.com/12439992/147378258-f2b91443-5b06-4add-a374-f666887c6572.png)
Submit -> Transfer

2021-12-26 11:46 UTC, Bigdragon123 commented
> ![image](https://user-images.githubusercontent.com/12439992/147378258-f2b91443-5b06-4add-a374-f666887c6572.png) Submit -> Transfer

alreday edited

2021-12-26 11:46 UTC, Bigdragon123 commented
> ![image](https://user-images.githubusercontent.com/12439992/147378249-81a4e59e-8587-49bd-b28c-d99a2cc4d031.png) approve button shoud start loading when sending tx

already edited

2021-12-27 05:21 UTC, merged